Switch to new SentrySwift library
jschmid/Corvus pull request #2
Opened 2016-09-13 21:42 UTC by edenman

@jschmid lemme know what you think (in particular, not sure if you'd want to make the version# actually 3.0 for this big of a change)

2016-09-14 19:19 UTC, jschmid commented on Corvus.m
> +  // TODO parse the actual symbols[c] string, if we're able to get the real ones
Can you please tell me what are those TODOs?

2016-09-14 19:20 UTC, jschmid commented on Corvus.podspec
> +  s.version      = "2.1.0"
As you suggested, I would prefer to use v3.0.0

2016-09-14 19:21 UTC, jschmid requested changes
Thanks for the PR!
I added a few comments.

2016-09-14 19:40 UTC, edenman commented on Corvus.m
> +  // TODO parse the actual symbols[c] string, if we're able to get the real ones
In my opinion, it'd be great to send up the full stacktrace to Sentry (only for `DDLogError`, probably?).  Unfortunately, the Corvus logger is called by CocoaLumberjack on a worker thread, where the original call stack is no longer available.  

- I've got a question out to the CocoaLumberjack folks [here](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/276) about this.
- Happy to remove the TODOs for now if you'd prefer, just lmk

2016-09-15 05:35 UTC, jschmid commented on Corvus.m
> +  // TODO parse the actual symbols[c] string, if we're able to get the real ones
Got it! 
Let's keep the todo then :+1:

2016-09-15 05:36 UTC, jschmid approved these changes
Thanks! I'll do a release tonight.

2016-09-15 16:48 UTC, merged

2016-09-15 17:47 UTC, jschmid commented
@edenman I can't release it to CocoaPods Trunk due to https://github.com/CocoaPods/CocoaPods/issues/5661 but I'll do when it's fixed!

2016-09-15 19:00 UTC, edenman commented
@jschmid thanks!

2016-12-12 18:17 UTC, edenman commented
@jschmid can you make this release please?  I'd like to finally switch over to Sentry-Swift so we can start taking advantage of https://docs.sentry.io/clients/cocoa/advanced/#change-event-before-sending-it

2016-12-13 07:58 UTC, jschmid commented
@edenman sorry for the delay. I'm not using this lib currently and forgot about the update.

Can you please try v3.1.4 ?

2016-12-17 00:14 UTC, edenman commented
Hm.  When I upgrade, my app crashes every time.  Not sure how this was working before :/  Logs:
```
2016-12-16 15:34:22.139437 recharge-consumer-ios[68766:2423485] [] __nwlog_err_simulate_crash_libsystem libsystem simulate crash unavailable "libsystem_network.dylib: netcore_create_control_socket :: socket(PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL) failed: [24] Too many open files"
2016-12-16 15:34:22.144255 recharge-consumer-ios[68766:2423485] [] netcore_create_control_socket socket(PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL) failed: [24] Too many open files, dumping backtrace:
        [x86_64] libnetcore-856.20.4
    0   libsystem_network.dylib             0x0000000114339682 __nw_create_backtrace_string + 123
    1   libsystem_network.dylib             0x000000011432d1a8 netcore_create_control_socket + 411
    2   libsystem_network.dylib             0x000000011434ff09 nw_get_host_stats + 62
    3   libnetwork.dylib                    0x00000001162f378b nw_endpoint_resolver_start_next_child + 1382
    4   libdispatch.dylib                   0x00000001140e50cd _dispatch_client_callout + 8
    5   libdispatch.dylib                   0x00000001140c11c3 _dispatch_continuation_pop + 1091
    6   libdispatch.dylib                   0x00000001140d61e2 _dispatch_source_latch_and_call + 195
    7   libdispatch.dylib                   0x00000001140ced7d _dispatch_source_invoke + 1098
    8   libdispatch.dylib                   0x00000001140c312c _dispatch_queue_serial_drain + 941
    9   libdispatch.dylib                   0x00000001140c3b9f _dispatch_queue_invoke + 1073
    10  libdispatch.dylib                   0x00000001140c63b7 _dispatch_root_queue_drain + 720
    11  libdispatch.dylib                   0x00000001140c608b _dispatch_worker_thread3 + 123
    12  libsystem_pthread.dylib             0x000000011448f736 _pthread_wqthread + 1299
    13  libsystem_pthread.dylib             0x000000011448f211 start_wqthread + 13
2016-12-16 15:34:22.144536 recharge-consumer-ios[68766:2423485] [] __nwlog_err_simulate_crash_libsystem libsystem simulate crash unavailable "libsystem_network.dylib: nw_get_host_stats :: netcore_create_control_socket failed"
2016-12-16 15:34:22.144867 recharge-consumer-ios[68766:2423485] [] nw_get_host_stats netcore_create_control_socket failed, dumping backtrace:
        [x86_64] libnetcore-856.20.4
    0   libsystem_network.dylib             0x0000000114339682 __nw_create_backtrace_string + 123
    1   libsystem_network.dylib             0x000000011434ffa6 nw_get_host_stats + 219
    2   libnetwork.dylib                    0x00000001162f378b nw_endpoint_resolver_start_next_child + 1382
    3   libdispatch.dylib                   0x00000001140e50cd _dispatch_client_callout + 8
    4   libdispatch.dylib                   0x00000001140c11c3 _dispatch_continuation_pop + 1091
    5   libdispatch.dylib                   0x00000001140d61e2 _dispatch_source_latch_and_call + 195
    6   libdispatch.dylib                   0x00000001140ced7d _dispatch_source_invoke + 1098
    7   libdispatch.dylib                   0x00000001140c312c _dispatch_queue_serial_drain + 941
    8   libdispatch.dylib                   0x00000001140c3b9f _dispatch_queue_invoke + 1073
    9   libdispatch.dylib                   0x00000001140c63b7 _dispatch_root_queue_drain + 720
    10  libdispatch.dylib                   0x00000001140c608b _dispatch_worker_thread3 + 123
    11  libsystem_pthread.dylib             0x000000011448f736 _pthread_wqthread + 1299
    12  libsystem_pthread.dylib             0x000000011448f211 start_wqthread + 13
2016-12-16 15:34:22.146119 recharge-consumer-ios[68766:2423485] [] __nwlog_err_simulate_crash_libsystem libsystem simulate crash unavailable "libsystem_network.dylib: nw_route_get_ifindex :: socket(PF_ROUTE, SOCK_RAW, PF_ROUTE) failed: [24] Too many open files"
2016-12-16 15:34:22.146524 recharge-consumer-ios[68766:2423485] [] nw_route_get_ifindex socket(PF_ROUTE, SOCK_RAW, PF_ROUTE) failed: [24] Too many open files, dumping backtrace:
        [x86_64] libnetcore-856.20.4
    0   libsystem_network.dylib             0x0000000114339682 __nw_create_backtrace_string + 123
    1   libsystem_network.dylib             0x000000011432e7d1 nw_route_get_ifindex + 774
    2   libsystem_network.dylib             0x000000011434612b nw_path_simulator_get_path_result + 145
    3   libsystem_network.dylib             0x0000000114345eb0 nw_path_create_evaluator_for_endpoint + 289
    4   libnetwork.dylib                    0x00000001162dbde1 nw_endpoint_handler_start + 415
    5   libnetwork.dylib                    0x00000001162f3ae5 nw_endpoint_resolver_start_next_child + 2240
    6   libdispatch.dylib                   0x00000001140e50cd _dispatch_client_callout + 8
    7   libdispatch.dylib                   0x00000001140c11c3 _dispatch_continuation_pop + 1091
    8   libdispatch.dylib                   0x00000001140d61e2 _dispatch_source_latch_and_call + 195
    9   libdispatch.dylib                   0x00000001140ced7d _dispatch_source_invoke + 1098
    10  libdispatch.dylib                   0x00000001140c312c _dispatch_queue_serial_drain + 941
    11  libdispatch.dylib                   0x00000001140c3b9f _dispatch_queue_invoke + 1073
    12  libdispatch.dylib                   0x00000001140c63b7 _dispatch_root_queue_drain + 720
    13  libdispatch.dylib                   0x00000001140c608b _dispatch_worker_thread3 + 123
    14  libsystem_pthread.dylib             0x000000011448f736 _pthread_wqthread + 1299
    15  libsystem_pthread.dylib             0x000000011448f211 start_wqthread + 13
...
```
(the logs are flooded with hundreds of these stacktraces and the app eventually crashes)

SentrySwift 1.3.0
Swift 2.3
XCode 8.1 beta (8T47)
iPhone SE Simulator running 10.1
CocoaLumberjack 2.4.0 + Corvus 1.3.4

I'm setting up Sentry+Corvus in my AppDelegate's `didFinishLaunchingWithOptions` method thusly:
```
		let sentryClient = SentryClient(dsnString: myDSN)!
		SentryClient.shared = sentryClient
		sentryClient.startCrashHandler()
		DDLog.addLogger(Corvus.sharedInstance(), withLevel: .Warning)
```

Things I've tried:
- removing Corvus entirely: no crash
- switching Corvus back to calling captureMessage (with no stacktrace stuff): still crashes

Maybe it's something about the fact that we're calling SentrySwift from the CocoaLumberjack worker thread?

2016-12-17 00:39 UTC, edenman commented
Tried wrapping `captureMessage` with
```
		dispatch_async(dispatch_get_main_queue(), ^{
			[[SentryClient shared] captureMessage:logMsg level:sentryLogLevel];
		});
```
no luck, still crashes :(

2016-12-17 00:53 UTC, edenman commented
Added some logging to SentrySwift, looks like i'm getting a bunch of 429 response codes, presumably because I'm sending a ton of log messages to Sentry and it's not batching/throttling them at all 😭

2016-12-19 20:31 UTC, edenman commented
Filed as https://github.com/getsentry/sentry-swift/issues/96 bc I'm now pretty certain this isn't a Corvus issue.  Sorry for the noise :)

2016-12-20 09:42 UTC, jschmid commented
Thanks for the update! Glad to see that one's work is used by others!

Let me know if it's fixed. Thanks!